// Auto-generated by data/prepare_data.py — do not edit.
// Regenerate via: cd data && python prepare_data.py

export type Energy = "Totale" | "Électricité" | "Gaz";
export type Sector =
  | "agriculture" | "industrie" | "résidentiel" | "tertiaire" | "autre" | "totale";

export interface Department {
  year: number;
  code: string;
  name: string;
  region: string;
  lat: number | null;
  lon: number | null;
  population: number | null;
  consumption: Record<Energy, Record<Sector, number>>;
}

export interface AnomalyZScoreEntry {
  codes: string[];
  scores: number[];
}

export interface AnomalyIQREntry {
  codes: string[];
  q1: number;
  q3: number;
  iqr: number;
  excess: number[];
}

export interface AnomalyIForestEntry {
  codes: string[];
  scores: number[];
}

export interface AnomalyDataset {
  zscore: Record<string, AnomalyZScoreEntry>;
  iqr: Record<string, AnomalyIQREntry>;
  iforest: Record<string, AnomalyIForestEntry>;
  thresholds: {
    zscore: number[];
    iqr: number[];
    iforest: number[];
  };
}

export interface ClusterDescription {
  id: number;
  label: string;
  dominant_sector: string;
  size: number;
  centroid_per_capita: number[];
}

export interface ClusterAssignment {
  code: string;
  cluster: number;
}

export interface ClustersDataset {
  year_used: number;
  k_chosen: number;
  silhouette_score: number;
  method: string;
  feature_columns: string[];
  clusters: ClusterDescription[];
  assignments: ClusterAssignment[];
}

export interface Prediction {
  code: string;
  sector: string;
  year: number;
  point: number;
  ci_low: number;
  ci_high: number;
}

export interface PredictionsDataset {
  method: string;
  warning: string;
  predictions: Prediction[];
}
